# Generated by Django 6.0 on 2025-12-27 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AirSpace', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('xp_per_message', models.IntegerField(default=2)),
                ('aura_per_like', models.IntegerField(default=5)),
                ('aura_per_dislike', models.IntegerField(default=10)),
                ('announcement_min_xp', models.IntegerField(default=500)),
                ('subscription_packages', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
