# Generated by Django 6.0 on 2025-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_musictrack_siteconfig_default_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='audio_url',
            field=models.URLField(default=1, help_text='Paste stream link here', max_length=500),
            preserve_default=False,
        ),
    ]
