# Generated by Django 6.0 on 2025-12-29 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_musictrack_audio_file_musictrack_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='chat.musictrack'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='category',
            field=models.CharField(choices=[('lofi', 'Lofi / Chill'), ('bollywood', 'Hindi / Urdu'), ('hollywood', 'Hollywood / English'), ('phonk', 'Phonk / Gym')], default='lofi', max_length=20),
        ),
        migrations.CreateModel(
            name='MusicSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
