# Generated by Django 6.0 on 2025-12-31 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profile_favorites_alter_musictrack_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='maintenance_mode',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='category',
            field=models.CharField(choices=[('love', 'Love / Romantic'), ('sad', 'Sad / Heartbreak'), ('peaceful', 'Peaceful / Healing'), ('travel', 'Travel / Vibe'), ('mashup', 'Mashups / Remix')], default='love', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='aura_per_like',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='xp_per_message',
            field=models.IntegerField(default=10),
        ),
    ]
