# Generated by Django 6.0 on 2025-12-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
