# Generated by Django 6.0 on 2026-01-06 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_profile_is_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='daily_login_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daily_msg_bonus_xp',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='streak_recover_cost',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('highest_streak', models.IntegerField(default=0)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('recovery_ads_watched', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login_claimed', models.BooleanField(default=False)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('msg_bonus_claimed', models.BooleanField(default=False)),
                ('first_like_received', models.BooleanField(default=False)),
                ('xp_ads_watched', models.IntegerField(default=0)),
                ('aura_ads_watched', models.IntegerField(default=0)),
                ('booster_claimed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
