# Generated by Django 6.0 on 2026-01-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_siteconfig_daily_login_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='streak_bonus_30_day',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='streak_bonus_7_day',
            field=models.IntegerField(default=500),
        ),
    ]
